export const AUTH_ROUTE = '/auth'
export const REQ_ROUTE = '/my'
export const ERR_ROUTE = '/404'
export const CREATE_ROUTE = '/create'
export const ADMIN_ROUTE = '/admin'
export const INFO_ROUTE = '/info'
export const MESSAGES_ROUTE = '/messages'